fix: some bug
vaanah/frontend-client pull request #202
Opened 2021-08-30 17:30 UTC by MbayeJacques

2021-08-30 17:56 UTC, aliouneKanouteTerinnova commented
Hi Mbaye, please give more explicit commit message and give an explicit description to your pull requests to. So that, the review would be easy for us.

2021-08-30 18:10 UTC, aliouneKanouteTerinnova requested changes
Hi Mbaye, please give more explicit commit message and give an explicit description to your pull requests to. So that, the review would be easy for us.

2021-08-31 08:50 UTC, MbayeJacques commented
ok @aliouneKanouteTerinnova

2021-08-31 09:56 UTC, FatmaGayeLO approved these changes

2021-08-31 10:07 UTC, merged